language: node_js
node_js:
  - "6"
  - "8"
  - "10"
script:
  - npm run prepublish
notifications:
  email:
    on_success: change
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
